// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ArticleTags string
	Articles    string
	Comments    string
	Favorites   string
	Follows     string
	Tags        string
	Users       string
}{
	ArticleTags: "article_tags",
	Articles:    "articles",
	Comments:    "comments",
	Favorites:   "favorites",
	Follows:     "follows",
	Tags:        "tags",
	Users:       "users",
}
