output   = "../entity"
wipe     = true
pkgname  = "entity"

[mysql]
dbname = "gforum"
host = "localhost"
port = 3306
user = "root"
pass = "secret"
sslmode = "false"
[auto-columns]
created = "createdAt"
updated = "updatedAt"

