version: 3
tasks:
  checkDb:
    desc: check db
    cmds:
      -  schema/forum/docker/wait-for-it.sh -t 5 localhost:3306
  dbimport:
    desc: import sql script
    cmds:
      - bin/dbimport -db schema/forum/sql -path schema/forum
  codegen:
    desc: Schema generation
    dir:  schema/forum
    deps:
      - checkDb
    cmds:
      - sqlboiler mysql
  podman:
    desc: start mysql docker
    dir: schema/forum
    cmds:
      - podman-compose up -d